### ISSUE TITLE
Missing converesion info for `image_joint_convnext_large/model_final_4c.pth`

### ISSUE THREAD

**Issue by bhack** [MasterBin-IIAU/UNINEXT#10]
https://github.com/MasterBin-IIAU/UNINEXT/blob/cc24f2470d546b91218a4bf72ab4846f4ae3033b/projects/UNINEXT/configs/video_joint_convnext_large.yaml#L4

But the data preparation Markdown doesn't include this step:
https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md

**Comment by MasterBin-IIAU** [comment]
@bhack Hi, thanks for pointing this out. Please run [convert_3c_to_4c_pth_convnext.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/conversion/convert_3c_to_4c_pth_convnext.py) to get outputs/image_joint_convnext_large/**model_final_4c.pth** from outputs/image_joint_convnext_large/**model_final.pth**

**Comment by bhack** [comment]
Are the hardcoded paths ok? Also where is the source model in the data markdown?

**Comment by MasterBin-IIAU** [comment]
Hi，source nodels can be found in assets/MODEL_ZOO.md

在 2023-03-21 07:09:22，bhack ***@***.***> 写道：

**Comment by bhack** [comment]
Can you fix the data preparation doc?
https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md

**Comment by MasterBin-IIAU** [comment]
@bhack Hi, we have updated [MODEL_ZOO.md](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/MODEL_ZOO.md#stage-3-video-level-joint-training) about the conversion scripts. We also change the original scripts (conversion/convert_3c_to_4c_pth.py, etc) by using command-line args.

**Comment by bhack** [comment]
I hope that you can clean up the folder organization a bit as in the configuration file you are using:

` WEIGHTS: "outputs/image_joint_convnext_large/model_final_4c.pth" `
