### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'projects/UNINEXT/bert-base-uncased'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by panchengl** [MasterBin-IIAU/UNINEXT#11]
hello, when i use this command :
python3 projects/UNINEXT/demo.py --config-file projects/UNINEXT/configs/image_joint_r50.yaml --input assets/demo.jpg --output demo/detection.jpg --task detection --opts MODEL.WEIGHTS outputs/image_joint_r50/model_final.pth 

encountered an error error like this:
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'projects/UNINEXT/bert-base-uncased'. Use `repo_type` argument if needed.

**Comment by changsubi** [comment]
you install Pretrained Weights
(https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md)
Pretrained Weights
Language Model (BERT-base)

mkdir -p projects/UNINEXT/bert-base-uncased
cd projects/UNINEXT/bert-base-uncased
wget -c https://huggingface.co/bert-base-uncased/resolve/main/config.json
wget -c https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt
wget -c https://huggingface.co/bert-base-uncased/resolve/main/pytorch_model.bin
cd ../../..
Visual Backbones

mkdir -p weights
cd weights
# R50
wget -c https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/torchvision/R-50.pkl
# ConvNeXt-Large
wget -c https://dl.fbaipublicfiles.com/convnext/convnext_large_22k_1k_384.pth
# Convert ConvNeXt-Large
cd ..
python3 conversion/convert_convnext.py --source_model weights/convnext_large_22k_1k_384.pth --output_model weights/convnext_large_22k_1k_384_new.pth
python3 projects/UNINEXT/convert_pth2pkl.py weights/convnext_large_22k_1k_384_new.pth weights/convnext_large_22k_1k_384_new.pkl
# ViT-Huge
wget -c https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MAE/mae_pretrain_vit_huge_p14to16.pth

**Comment by MasterBin-IIAU** [comment]
@panchengl Hi, as @changsubi said, please first download the pretrained weights of [language model](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md#pretrained-weights) and our [image_joint_r50 model](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/MODEL_ZOO.md)

**Comment by panchengl** [comment]
thank you very much for your reply, the anwser solved my problem @MasterBin-IIAU @changsubi
