### ISSUE TITLE
why use gt_masks instead of gt_boxes

### ISSUE THREAD

**Issue by zwhus** [MasterBin-IIAU/UNINEXT#14]
Thanks to the author for such a great job!
I have a question about masks,
Why use gt_masks instead of gt_boxes after data augmentation, if you use gt_bboxes directly, how much will the final experimental results differ.
'''
dataset_mapper_uni_vid.UniVidDatasetMapper
if instances.has("gt_masks"):
    instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
'''

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, the reasons are as follows. After data augmentions such as random crop, some instances may be truncated by new image borders. In these cases, directly computing new gt_boxes based on the original gt boxes may be inaccurate. However, if we use gt_masks, then the new gt_boxes will still be accurate. You can refer to this image for better understanding.
https://user-images.githubusercontent.com/26833433/107129891-967e6a80-687d-11eb-96e1-c307f49dfa94.jpg
