### ISSUE TITLE
Pre-train checkpoint 

### ISSUE THREAD

**Issue by stlmx** [MasterBin-IIAU/UNINEXT#16]
It seems that the model should be pre-trained on Object-365 datasets. However, We don't have enough computing resources. 
So, could you please offer the pre-trained checkpoint ?

Thanks very much !!

**Comment by MasterBin-IIAU** [comment]
@stlmx Hi, sure, we have provided pretrained weights you need in [MODEL_ZOO.md](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/MODEL_ZOO.md#stage-1-pretraining). Please check models in Stage 1: Pretraining.

**Comment by stlmx** [comment]
Thanks a lot!!!
