### ISSUE TITLE
Error when convert pretrained weights to 4c

### ISSUE THREAD

**Issue by LingyvKong** [MasterBin-IIAU/UNINEXT#19]
For stage 3 pretrained weights, when running `python3 conversion/convert_3c_to_4c_pth.py`, I got this error:

Traceback (most recent call last):
  File "conversion/convert_3c_to_4c_pth.py", line 30, in <module>
    new_value[:, :-1, :, :] = v
RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [64, 3, 7, 7].  Tensor sizes: [64, 4, 7, 7]

**Comment by MasterBin-IIAU** [comment]
@LingyvKong Hi, did you change any command-line arguments? Please directly run ```python3 conversion/convert_3c_to_4c_pth.py```. Besides, download pretrained weights of ```image_joint_r50``` using the [link](https://maildluteducn-my.sharepoint.com/personal/yan_bin_mail_dlut_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyan%5Fbin%5Fmail%5Fdlut%5Fedu%5Fcn%2FDocuments%2Foutputs%2Fimage%5Fjoint%5Fr50&ga=1) in the MODEL_ZOO.md

**Comment by LingyvKong** [comment]
Thanks, the problem has been solved, I downloaded video_joint_r50 by mistake
