### ISSUE TITLE
Time consuming of model training

### ISSUE THREAD

**Issue by qq1018408006** [MasterBin-IIAU/UNINEXT#20]
It is a promising project in the field of unified network design.
According to the information provided in the paper, the model training process involves three stages and requires 32 and 16 A100 GPUs respectively. Could you please clarify how long the training process would take?

**Comment by MasterBin-IIAU** [comment]
@qq1018408006 Hi, for UNINEXT with ResNet-50 backbone, training time in each stage is listed as follows.
Stage1: 3~4 days on 32 A100
Stage2: less than 1 day on 16 A100
Stage3: 2 days on 16 A100
For UNINEXT with larger backbones, training time will be longer.

**Comment by qq1018408006** [comment]
@MasterBin-IIAU Thanks for your reply! It looks much expensive.
