### ISSUE TITLE
Where can I find the Prompt  Generation part for template image?

### ISSUE THREAD

**Issue by Nightwatch-Fox11** [MasterBin-IIAU/UNINEXT#23]
Hello, where can I find the Prompt  Generation part for template image?

**Comment by MasterBin-IIAU** [comment]
@Nightwatch-Fox11 Hi, please refer to [coco_forward_sot](https://github.com/MasterBin-IIAU/UNINEXT/blob/16dc33d9fd9cfb2f423f69dc104f2f326efce0b0/projects/UNINEXT/uninext/models/ddetrs_vid_dn.py#L217) and  [get_template_4c](https://github.com/MasterBin-IIAU/UNINEXT/blob/16dc33d9fd9cfb2f423f69dc104f2f326efce0b0/projects/UNINEXT/uninext/models/ddetrs_vid_dn.py#L95)

**Comment by Nightwatch-Fox11** [comment]
Thanks for your reply!
