### ISSUE TITLE
Google Colab for inference on pretrained models

### ISSUE THREAD

**Issue by Q-Tran** [MasterBin-IIAU/UNINEXT#24]
Hello,

I believe there were people who asked for examples and colab examples. I used colab to run the code here and thought it would be beneficial if I shared it here.

https://colab.research.google.com/drive/1b0BT1qROm6aQmNKwJ5nPspLkZyOCrBj7?usp=sharing

Thank you so much and a great job on the code and paper! Congrats on getting your paper accepted!

**Comment by MasterBin-IIAU** [comment]
@Q-Tran Hi, thank you for providing such detailed colab example! Sincerely thanks for your contribution.
