### ISSUE TITLE
Performance of REC & RES without stage I O365 training?

### ISSUE THREAD

**Issue by RunpeiDong** [MasterBin-IIAU/UNINEXT#26]
Hi @MasterBin-IIAU,

Thanks for your wonderful work!

Could you please tell me the performance of REC & RES without stage one training (O365 detection)? This could help me a lot.

Regards,
Runpei

**Comment by MasterBin-IIAU** [comment]
@RunpeiDong Hi, in my memory, the performance of REC&RES may drop about 1.5 without Objects365 pretraining.

**Comment by RunpeiDong** [comment]
Got it. Thanks for your reply.
