### ISSUE TITLE
Results much worse than paper. Is it possible I do not have the correct models?

### ISSUE THREAD

**Issue by Q-Tran** [MasterBin-IIAU/UNINEXT#31]
The following shows results for OVIS and youtube-VIS:

![ovis_vis](https://user-images.githubusercontent.com/10189171/234146905-63c6ba20-ce78-432c-bfd7-cd9529e36d37.png)
![youtube_vis](https://user-images.githubusercontent.com/10189171/234146928-e74c3342-a177-41e8-ae74-ce962249bef7.png)

I am running these using infer.sh and commenting out other tasks. I also added the flag --np 1 to each of the launch commands as I am running this all on a single 4090.

I followed the instructions in INSTALL.md and did the following.
1. downloaded the Language Model (BERT-base) according tho DATA.md
2. downloaded the RESNET 50 models for image and video from the MODEL_ZOO.md (step 2 and 3).
3.  Converted the 3c to 4c with the following python3 conversion/convert_3c_to_4c_pth.py
4. Downloaded the respective datasets and ran the corresponding infer.sh code

Some things that I am not sure about:

I did not download the pretrained models in DATA.md in the pretrained weights section as they seem to be the backbones before training on Object365.

Do I have the right BERT model?  It seems like I am downloading the base BERT model, but in the paper it says in section 4.1 that its parameters are trained in the first two stages. That BERT model doesn't seem to be in the MODEL_ZOO.md

**Comment by Q-Tran** [comment]
I'm thinking maybe these warnings also have to do with not loading the model properly
``
[04/25 14:53:43 fvcore.common.checkpoint]: [Checkpointer] Loading from outputs/image_joint_r50/model_final_4c.pth ...
WARNING [04/25 14:53:47 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
detr.adjust_layer.{bias, weight}
detr.reid_embed_head.0.layers.0.cross_attn.attention_weights.{bias, weight}
detr.reid_embed_head.0.layers.0.cross_attn.output_proj.{bias, weight}
detr.reid_embed_head.0.layers.0.cross_attn.sampling_offsets.{bias, weight}
detr.reid_embed_head.0.layers.0.cross_attn.value_proj.{bias, weight}
detr.reid_embed_head.0.layers.0.linear1.{bias, weight}
detr.reid_embed_head.0.layers.0.linear2.{bias, weight}
detr.reid_embed_head.0.layers.0.norm1.{bias, weight}
detr.reid_embed_head.0.layers.0.norm2.{bias, weight}
detr.reid_embed_head.0.layers.0.norm3.{bias, weight}
detr.reid_embed_head.0.layers.0.self_attn.out_proj.{bias, weight}
detr.reid_embed_head.0.layers.0.self_attn.{in_proj_bias, in_proj_weight}
detr.reid_embed_head.0.layers.1.cross_attn.attention_weights.{bias, weight}
detr.reid_embed_head.0.layers.1.cross_attn.output_proj.{bias, weight}
detr.reid_embed_head.0.layers.1.cross_attn.sampling_offsets.{bias, weight}
detr.reid_embed_head.0.layers.1.cross_attn.value_proj.{bias, weight}
detr.reid_embed_head.0.layers.1.linear1.{bias, weight}
detr.reid_embed_head.0.layers.1.linear2.{bias, weight}
detr.reid_embed_head.0.layers.1.norm1.{bias, weight}
detr.reid_embed_head.0.layers.1.norm2.{bias, weight}
detr.reid_embed_head.0.layers.1.norm3.{bias, weight}
detr.reid_embed_head.0.layers.1.self_attn.out_proj.{bias, weight}
detr.reid_embed_head.0.layers.1.self_attn.{in_proj_bias, in_proj_weight}
detr.reid_embed_head.0.ref_point_head.layers.0.{bias, weight}
detr.reid_embed_head.0.ref_point_head.layers.1.{bias, weight}
detr.reid_embed_head.1.layers.0.{bias, weight}
detr.reid_embed_head.1.layers.1.{bias, weight}
detr.reid_embed_head.1.layers.2.{bias, weight}
detr.sot_fuser.refine.0.{bias, weight}
detr.sot_fuser.refine.1.{bias, weight}
detr.sot_fuser.refine.2.{bias, weight}
detr.sot_fuser.refine.3.{bias, weight}
WARNING [04/25 14:53:47 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  detr.detr.iou_head.0.{bias, weight}
  detr.detr.iou_head.1.{bias, weight}
  detr.detr.iou_head.2.{bias, weight}
  detr.detr.iou_head.3.{bias, weight}
  detr.detr.iou_head.4.{bias, weight}
  detr.detr.iou_head.5.{bias, weight}
``

**Comment by MasterBin-IIAU** [comment]
You do not load our trained model. Please download the whole ``outputs/video_joint_r50`` rather than only ``model_final.pth`` from MODEL_ZOO.md. Remember that we need ``last_checkpoint``.

**Comment by Q-Tran** [comment]
Perfect. It is working. Thank you!

**Comment by pistil-K** [comment]
Why is this so? When I open the checkpoint, there is only one line of “model_final.pth” inside. Is there any difference between this and directly loading model_final.pth？
