### ISSUE TITLE
A question of task-specific performance (RVOS)

### ISSUE THREAD

**Issue by bo-miao** [MasterBin-IIAU/UNINEXT#32]
Hi,

Thanks for the excellent work!

May I have some details of the R-VOS performance (57.2) in Table 11 for comparison? 

Did you follow ReferFormer and perform joint training (combine Ref-COCO pseudo sequences and YouTube-VOS for training) or pretrain&finetune (pretrain on static Ref-COCO datasets and finetune on YouTube-VOS), or use some different strategies?

**Comment by MasterBin-IIAU** [comment]
Hi, we first pretrain UNINEXT on RefCOCO/g/+ then finetune UNINEXT jointly on RefCOCO/g/+ and Ref-Youtube-VOS.

**Comment by bo-miao** [comment]
Thanks for your timely response.

**Comment by bo-miao** [comment]
Could you kindly provide the J score and F score of the performance (57.2 J&F) for future works to compare? Thanks.
