### ISSUE TITLE
What does J&F 1st frame means

### ISSUE THREAD

**Issue by HaoZhang534** [MasterBin-IIAU/UNINEXT#34]
Dear authors, thank you for your great work. I saw you report "J&F 1st frame" in paperswithcode leader board, but I did not find the definition of this metric. Can you tell me about it? Thank you so much.

**Comment by MasterBin-IIAU** [comment]
@HaoZhang534 Hi Hao, "J&F 1st frame" in paperswithcode is just the J&F used in R-VOS of our paper.
