### ISSUE TITLE
Models mismatches when load

### ISSUE THREAD

**Issue by samuruph** [MasterBin-IIAU/UNINEXT#43]
Hello, I am trying to reproduce results for SOT task (on LaSOT_ext) in testing, since I would like to analyzed the trained model on another dataset.

Specifically, I have followed all the procedure highlighted in DATA.md for data preparation (models and dataset).
Moreover, I have downloaded the models in MODEL_ZOO.md (image_joint_r50, image_joint_convnext_large, and image_joint_vit_huge_32g from Stage 2) and converted from 3c to 4c with your script.
Finally, run assets/infer.sh file.

Anyway, following the procedure, I am still getting some mismatches when loading the models (BERT and image_joint_r50).

What Iam I doing wrong?

**Comment by MasterBin-IIAU** [comment]
Hi, to evaluate on video-level tasks like SOT, you should download models like video_joint_r50. image_joint_xxx are not necessary. Please notice that you need to download the whole folder including the file called last_checkpoint.

**Comment by MasterBin-IIAU** [comment]
Please refer to this issue (https://github.com/MasterBin-IIAU/UNINEXT/issues/31) for better understanding.

**Comment by samuruph** [comment]
Ok got it! 
But when running infer.sh for SOT, in video_joint_r50.yaml config file, it has been defined that "WEIGHTS: "outputs/image_joint_r50/model_final_4c.pth"", and so the script is loading the model from image_joint_r50. Should I change this line to take correct models?

Moreover when trying to convert the model from 3c to 4c, I am getting this error:
```RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [64, 3, 7, 7].  Tensor sizes: [64, 4, 7, 7]```

Instead for BERT model, I don't quite get why I have different model structure, since I have downloaded following your procedure.

**Comment by MasterBin-IIAU** [comment]
Hi, "WEIGHTS" means pretrained weights loaded for training. During the inference, we will load video_joint_xxx automatically by setting "--resume". So you don't need to make any change to yaml. 
For simplicity, you can also directly set WEIGHTS as None by setting [this line](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/configs/video_joint_r50.yaml#L16) as WEIGHTS: None
In this way, you don't need to download and transform image weights.

**Comment by samueleruffino99** [comment]
So I haven't quite get why we need to convert model weights with coversion scripts.
I get the "--resume" paramater with directory from which the pretrained model is loaded, but should I convert the weights anyway? Because it tries to import model_final_4c.pth during inference

**Comment by samuruph** [comment]
Ok I got it now!
Anyway I have still some error when loading BERT.-based model, it seems it does not match

**Comment by MasterBin-IIAU** [comment]
If it is just warning, no need to worry. It doesn't have influence.
