### ISSUE TITLE
SOT test takes 21/22 hours on LaSOT_ext

### ISSUE THREAD

**Issue by samuruph** [MasterBin-IIAU/UNINEXT#44]
Hello I am trying to test the ResNet-50 based model on LaSOT_ext dataset for SOT task.
I have available 4 GPUs only, and the inference takes forever (around 21/22 hourse).
Is it supposed to be like that or I am doing something wrong? I was expected a couple of hours at maximum :)

Thank you!

**Comment by MasterBin-IIAU** [comment]
Hi, I think the time is normal for LaSOT_ext because it has some really long sequences. I think you can try evaluating on TrackingNet or GOT-10K for fast evaluation.

**Comment by MasterBin-IIAU** [comment]
By the way, some datasets of VOS like DAVIS-17 is quite small and very suitable for fast validation. If the performance on DAVIS can be reproduced, I believe that the results on LaSOT-ext can also be validated too.

**Comment by samuruph** [comment]
Ok thank you!!
