### ISSUE TITLE
Adding new backbone

### ISSUE THREAD

**Issue by emrekeles-arch** [MasterBin-IIAU/UNINEXT#45]
I want to use the NextViT transformer model as a backbone in uninext, how do I register the model and how do I use it? Do you have a document or resource about this?

Thanks for help

**Comment by MasterBin-IIAU** [comment]
Hi, you can refer to our [vit.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/uninext/backbone/vit.py) and [convnext.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/uninext/backbone/convnext.py). Especially, you can imitate [Class D2ViT](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/backbone/vit.py#L379) and [Class D2ConvNext](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/backbone/convnext.py#L198)

**Comment by MasterBin-IIAU** [comment]
By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)

**Comment by emrekeles-arch** [comment]
How can I make the model train using the backbone I just added?

**Comment by emrekeles-arch** [comment]
> By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)

I made the changes you mentioned, but I am getting the following error, what is the reason?

  File "/root/.local/lib/python3.10/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'D2NextViT' found in 'BACKBONE' registry!"

**Comment by MasterBin-IIAU** [comment]
> > By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)
> 
> I made the changes you mentioned, but I am getting the following error, what is the reason?
> 
> File "/root/.local/lib/python3.10/site-packages/fvcore/common/registry.py", line 71, in get raise KeyError( KeyError: "No object named 'D2NextViT' found in 'BACKBONE' registry!"

Hi, please also add your backbone [here](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/__init__.py#L9)

**Comment by emrekeles-arch** [comment]
> > > By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)
> > 
> > 
> > I made the changes you mentioned, but I am getting the following error, what is the reason?
> > File "/root/.local/lib/python3.10/site-packages/fvcore/common/registry.py", line 71, in get raise KeyError( KeyError: "No object named 'D2NextViT' found in 'BACKBONE' registry!"
> 
> Hi, please also add your backbone [here](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/__init__.py#L9)

Thank you, it works!

**Comment by emrekeles-arch** [comment]
> > > By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)
> > 
> > 
> > I made the changes you mentioned, but I am getting the following error, what is the reason?
> > File "/root/.local/lib/python3.10/site-packages/fvcore/common/registry.py", line 71, in get raise KeyError( KeyError: "No object named 'D2NextViT' found in 'BACKBONE' registry!"
> 
> Hi, please also add your backbone [here](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/__init__.py#L9)

Can you give me an idea about what problems I may encounter when integrating a different model into the backbone, what I may need to adjust?

Thank you

**Comment by emrekeles-arch** [comment]
> > > By the way, you also need to make corresponding changes in yaml files. You can refer to [image_joint_vit_huge_32g.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_vit_huge_32g.yaml) and [image_joint_convnext_large.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/image_joint_convnext_large.yaml)
> > 
> > 
> > I made the changes you mentioned, but I am getting the following error, what is the reason?
> > File "/root/.local/lib/python3.10/site-packages/fvcore/common/registry.py", line 71, in get raise KeyError( KeyError: "No object named 'D2NextViT' found in 'BACKBONE' registry!"
> 
> Hi, please also add your backbone [here](https://github.com/MasterBin-IIAU/UNINEXT/blob/5ab03865d05d61c23799ae0bd3305b160ceb3f34/projects/UNINEXT/uninext/__init__.py#L9)

How can I make the model train using the backbone I just added?
