### ISSUE TITLE
bdd download error

### ISSUE THREAD

**Issue by zwhus** [MasterBin-IIAU/UNINEXT#5]
Thanks to the author for such a great job!
But when I use conversion/download_bdd.py, 
" https://bdd-data-storage-release.s3.us-west-2.amazonaws.com/bdd100k/2021/bdd100k_seg_track_20_labels_trainval.zip" and "https://bdd-data-storage-release.s3.us-west-2.amazonaws.com/bdd100k/2021/bdd100k_ins_seg_labels_trainval.zip" can't download, how to solve this problem.

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, it seems the original links of these two files from BDD100K official website have been broken. We have just upload these two files to our onedrive. You can manually download [bdd100k_ins_seg_labels_trainval.zip](https://maildluteducn-my.sharepoint.com/:u:/g/personal/yan_bin_mail_dlut_edu_cn/EdisvabQkchLpcPWyi59X8QB7XBLyGkKS8-HUH1Q2FGi9A?e=qkgyi5) and 
[bdd100k_seg_track_20_labels_trainval.zip](https://maildluteducn-my.sharepoint.com/:u:/g/personal/yan_bin_mail_dlut_edu_cn/EVQ0CMFo54FIhvkZzLDFTkYBENElXH-bXLNXZOCbf0dxoQ?e=Meb8R5) from onedrive.

**Comment by zwhus** [comment]
Thanks, I will try it again!

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, have the answer solve your issue? If the issue has been solved, please consider closing it. Thanks  :)

**Comment by zwhus** [comment]
Now, i have new question, when i run prepare_bdd.sh, Error while finding module specification for 'bdd100k.label.to_coco' (ModuleNotFoundError: No module named 'bdd100k'), how tosolve it ?

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, please refer to [MOTS](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/TEST.md#mots) to install bdd100k package. 
```
git clone https://github.com/bdd100k/bdd100k.git
cd bdd100k
python3 setup.py develop --user
pip3 uninstall -y scalabel
pip3 install --user git+https://github.com/scalabel/scalabel.git
pip3 install -U numpy
cd ..
```

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, I don't quite understand the question. According to [VIS Tutotial](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md#vis), Youtube-VIS dataset can be downloaded from [colab](https://codalab.lisn.upsaclay.fr/competitions/6064#participate-get_data). Then you can unzip zipped files and put them under datasets folder.

**Comment by zwhus** [comment]
ok, thanks for your reply

**Comment by zwhus** [comment]
HI， when i use [VIS Tutotial](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/assets/DATA.md#vis) to downlaod youtube_vis_2019, the annaotations id

**Comment by MasterBin-IIAU** [comment]
@zwhus Hi, please just rename train.json and valid.json to instances_train_sub.json and instances_val_sub.json respectively.

**Comment by zwhus** [comment]
ok，thanks,
