### ISSUE TITLE
MOT on video

### ISSUE THREAD

**Issue by chema-344** [MasterBin-IIAU/UNINEXT#8]
Hello,

Great work!!. Could you provide an example of MOT using a video as input?

I'm having trouble trying.

Many thanks

**Comment by MasterBin-IIAU** [comment]
Hi, we have upload an [demo video](https://maildluteducn-my.sharepoint.com/:u:/g/personal/yan_bin_mail_dlut_edu_cn/EZAmK7I_jBhAtRMTF_Xsk-UBhLjC-wH9pWRxDVS-cMYwAg?e=ume6td) from BDD100K MOT val to our onedrive. Please download and unzip demo_bdd.zip then you can get a folder with structure `datasets/bdd`. This folder should contain video frames and the corresponding json file. 

Then open your local `projects/UNINEXT/uninext/uninext_vid.py` then change [line 53](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L53) to `self.debug_only=True` and comment out [line 396](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L396) to [line 399](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L399). 

Finally, run the following command `python3 launch.py --nn 1 --np 1 --eval-only --uni 1 --config-file projects/UNINEXT/configs/eval-vid/video_joint_r50_eval_mot.yaml --resume OUTPUT_DIR outputs/video_joint_r50 MODEL.USE_IOU_BRANCH False`. Then you should see the detection and tracking results drawn on the original frames. Specifically, **detection** results starts with `frame_det` and **different colors represent different object classes**. Besides, **tracking** results starts with `frame_track` and **different colors represent different object ID**. Enjoy :)

**Comment by chema-344** [comment]
Thanks!!!

**Comment by beratersari** [comment]
> Hi, we have upload an [demo video](https://maildluteducn-my.sharepoint.com/:u:/g/personal/yan_bin_mail_dlut_edu_cn/EZAmK7I_jBhAtRMTF_Xsk-UBhLjC-wH9pWRxDVS-cMYwAg?e=ume6td) from BDD100K MOT val to our onedrive. Please download and unzip demo_bdd.zip then you can get a folder with structure `datasets/bdd`. This folder should contain video frames and the corresponding json file.
> 
> Then open your local `projects/UNINEXT/uninext/uninext_vid.py` then change [line 53](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L53) to `self.debug_only=True` and comment out [line 396](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L396) to [line 399](https://github.com/MasterBin-IIAU/UNINEXT/blob/2f08e18284a891d26260e9e0c661db2d4e4d7d63/projects/UNINEXT/uninext/uninext_vid.py#L399).
> 
> Finally, run the following command `python3 launch.py --nn 1 --np 1 --eval-only --uni 1 --config-file projects/UNINEXT/configs/eval-vid/video_joint_r50_eval_mot.yaml --resume OUTPUT_DIR outputs/video_joint_r50 MODEL.USE_IOU_BRANCH False`. Then you should see the detection and tracking results drawn on the original frames. Specifically, **detection** results starts with `frame_det` and **different colors represent different object classes**. Besides, **tracking** results starts with `frame_track` and **different colors represent different object ID**. Enjoy :)

that worked for me but just write the image files with bboxes. How can show it with segmented pixels? Could you help me?
